### PR TITLE
Various spelling, proofreading, wording fixes.

### PR DESCRIPTION
**Pull request by nissa-seru**
Thanks for translating this mod to EN! I've made some spelling/proofreading/wording changes to improve readability during my playthroughs - submitting as a PR in case helpful to continued progress in EN localization of the mod.

Also updated the game version in [a12dd51](https://github.com/dilinganye/XXVIIBattleGroup_EN/pull/1/commits/a12dd51134ccbf14ce52363f994f905c175b0e5a) to prevent the mod from being auto-disabled due to specifying 0.96a as a dependency.

### CODE REVIEW

**Comment by nissa-seru** [comment]
Fixed some more issues that I came across during playtesting.

**Comment by nissa-seru** [comment]
Added support for [Version Checker](https://fractalsoftworks.com/forum/index.php?topic=8181.0) in [59b8d66](https://github.com/dilinganye/XXVIIBattleGroup_EN/pull/1/commits/59b8d66927a51b0a0c51c59273c665fa848c0745) - the only maintenance required should be to increment the patch version in XXVIIBattleGroup.version whenever it is incremented in mod_info.json.

**Review by dilinganye — APPROVED** [review]
Thanks for this fixes, great thanks to nissa-seru

**Comment by nissa-seru** [comment]
Hi @dilinganye, just sharing as a quick note; I'm unable to merge this PR into the base branch (even after your approval.) Given the permission setup of the repo, I think you may need to merge the PR yourself to apply the updates.

**Pull request merged**
